"""
Django settings for zeta_sa project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()

environ.Env.read_env(os.path.join(BASE_DIR,'file.env'))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+u+ln9g&y=s)^id!so2i@&97kdfz&p%i&7j^bzqahom7!*7j%5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = ["zetasassisrl.com "]
CSRF_TRUSTED_ORIGINS = ["https://zetasassisrl.com"]



# Application definition
AUTH_USER_MODEL = 'accounts.Account'



INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'zeta',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zeta_sa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zeta_sa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE':'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),  
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/



STATIC_URL = 'static/'
MEDIA_URL = '/media/'

# if DEBUG:
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# else:
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('EMAIL_HOST_USER')
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False







UNFOLD = {
    "SITE_HEADER": "ZETA-SASSI S.R.L.",
    "SHOW_SIDEBAR": True,
    "SITE_TITLE": "ZETA-SASSI S.R.L.",
    "SITE_SUBHEADER": "ZETA-SASSI S.R.L. Admin Panel",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("logo/zet_wh.webp"),
        "dark": lambda request: static("logo/zet_wh.webp"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("logo/zet_wh.webp"),
        "dark": lambda request: static("logo/zet_wh.webp"),
    },
    "DASHBOARD": {
        "show_search": True,
        "show_all_applications": True,
        "cards": [
            {
                "title": _("Users"),
                "icon": "group",
                "link": reverse_lazy("admin:accounts_account_changelist"),
                "description": _("Manage registered users."),
            },
            {
                "title": _("Products"),
                "icon": "storefront",
                "link": reverse_lazy("admin:accounts_product_changelist"),
                "description": _("Manage products."),
            },
            {
                "title": _("Orders"),
                "icon": "shopping_cart",
                "link": reverse_lazy("admin:accounts_order_changelist"),
                "description": _("Manage customer orders."),
            },
            {
                "title": _("Reviews"),
                "icon": "rate_review",
                "link": reverse_lazy("admin:accounts_writtenreview_changelist"),
                "description": _("Manage product reviews."),
            },
        ],
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("User Management"),
                "icon": "account_circle",
                "collapsible": False,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "group",
                        "link": reverse_lazy("admin:accounts_account_changelist"),
                    },
                ],
            },
            {
                "title": _("Products"),
                "icon": "storefront",
                "collapsible": False,
                "items": [
                    {
                        "title": _("All Products"),
                        "icon": "electrical_services",
                        "link": reverse_lazy("admin:accounts_product_changelist"),
                    },
                   
                ],
            },
            {
                "title": _("Sales"),
                "icon": "shopping_cart",
                "collapsible": True,
                "separator": True,
                "items": [
                    {
                        "title": _("Orders"),
                        "icon": "receipt",
                        "link": reverse_lazy("admin:accounts_order_changelist"),
                    },
                    {
                        "title": _("Shopping Carts"),
                        "icon": "shopping_basket",
                        "link": reverse_lazy("admin:accounts_shoppingcart_changelist"),
                    },
                ],
            },
            {
                "title": _("Reviews & Feedback"),
                "icon": "rate_review",
                "collapsible": True,
                "separator": True,
                "items": [
                    {
                        "title": _("Product Reviews"),
                        "icon": "thumb_up",
                        "link": reverse_lazy("admin:accounts_writtenreview_changelist"),
                    },
                ],
            },
            {
                "title": _("Financials"),
                "icon": "account_balance",
                "collapsible": True,
                "separator": True,
                "items": [
                    {
                        "title": _("Bank Details"),
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy("admin:accounts_bankdetails_changelist"),
                    },
                ],
            },
        ],
    },
}
